### ISSUE TITLE
ERROR-[plugin vite:dep-scan] 报错

### ISSUE THREAD

**Issue by xiaozhimengmengda** [yh-zero/go-zero-admin-vue3#3]
node:v18.20.0
npm: 10.5.0
 [ERROR] [plugin vite:dep-scan] ENOENT: no such file or directory, open '/workspace/data/vue-project/go-zero-admin-vue3/src/components/sysModal/index.vue'
 
     node_modules/vite/node_modules/esbuild/lib/main.js:1426:27:
      1426 │         let result = await callback({
           ╵                            ^

    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at file:///workspace/data/vue-project/go-zero-admin-vue3/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41913:32
    at requestCallbacks.on-load (/workspace/data/vue-project/go-zero-admin-vue3/node_modules/vite/node_modules/esbuild/lib/main.js:1426:28)
    at handleRequest (/workspace/data/vue-project/go-zero-admin-vue3/node_modules/vite/node_modules/esbuild/lib/main.js:727:19)
    at handleIncomingPacket (/workspace/data/vue-project/go-zero-admin-vue3/node_modules/vite/node_modules/esbuild/lib/main.js:749:7)
    at Socket.readFromStdout (/workspace/data/vue-project/go-zero-admin-vue3/node_modules/vite/node_modules/esbuild/lib/main.js:677:7)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)

  This error came from the "onLoad" callback registered here:

    node_modules/vite/node_modules/esbuild/lib/main.js:1287:20:
      1287 │       let promise = setup({
           ╵                     ^

    at setup (file:///workspace/data/vue-project/go-zero-admin-vue3/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41912:19)
    at handlePlugins (/workspace/data/vue-project/go-zero-admin-vue3/node_modules/vite/node_modules/esbuild/lib/main.js:1287:21)
    at buildOrServeImpl (/workspace/data/vue-project/go-zero-admin-vue3/node_modules/vite/node_modules/esbuild/lib/main.js:974:5)
    at Object.buildOrServe (/workspace/data/vue-project/go-zero-admin-vue3/node_modules/vite/node_modules/esbuild/lib/main.js:780:5)
    at /workspace/data/vue-project/go-zero-admin-vue3/node_modules/vite/node_modules/esbuild/lib/main.js:2132:17
    at new Promise (<anonymous>)
    at Object.build (/workspace/data/vue-project/go-zero-admin-vue3/node_modules/vite/node_modules/esbuild/lib/main.js:2131:14)
    at build (/workspace/data/vue-project/go-zero-admin-vue3/node_modules/vite/node_modules/esbuild/lib/main.js:1978:51)
    at scanImports (file:///workspace/data/vue-project/go-zero-admin-vue3/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41785:11)

  The plugin "vite:dep-scan" was triggered by this import

    script:/workspace/data/vue-project/go-zero-admin-vue3/src/views/superAdmin/dictionary/modules/leftList/addModal.vue?id=0:35:7:
      35 │ import '@/components/sysModal/index.vue'
         ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by xiaozhimengmengda** [comment]
在tsconfig.json里面
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "types/**/*.d.ts",
    "build/*.ts"
  ]
  新增 "build/*.ts"解决了
